const SITE_URL = "https://brainrotgames.me";
const UPDATED = "2026-09-09";

const ARTICLES = {
  "choose-browser-game": {
    title: "How to Choose a Browser Game You’ll Actually Enjoy",
    category: "Getting Started",
    intro: "A large game library is useful only when it helps you make a good choice quickly. This guide gives you a simple way to match a browser game to your time, device, controls and preferred level of challenge.",
    sections: [
      ["Start with the session you want", ["The first question is not which genre is popular; it is how long you want to play. For a five-minute break, a short arcade, puzzle or casual game is usually a better fit than a game that needs a long introduction. If you have a longer session, adventure, simulation, strategy and progression-focused games can make more sense.", "Thinking about session length also prevents a common problem with browser libraries: opening several games and abandoning all of them because none matches the moment. Pick the experience you want first, then browse within that type."]],
      ["Check the control style", ["Controls can matter more than graphics. A game designed around a keyboard and mouse can feel awkward on a phone, while a touch-friendly game may be excellent on a tablet but less satisfying with a desktop mouse. Look for clues in the game page and, once the game opens, give the controls a short test before committing to a long session.", "If a game uses many keys, keep the keyboard visible or note the important actions before starting. For mouse-heavy games, a stable surface and a normal pointer speed make a bigger difference than small visual settings."]],
      ["Choose difficulty deliberately", ["Difficulty is not a quality score. A demanding puzzle can be exactly right when you want concentration and completely wrong when you want to relax. Likewise, a simple clicker or casual game can be satisfying when you want a low-pressure session.", "If you are unsure, start with a category you already understand and choose a game with a clear objective. Once you know how the site and controls behave, experiment with more specialized genres."]],
      ["Use categories as filters, not guarantees", ["A category such as Racing or Puzzle is a useful starting point, but games inside a broad category can feel very different. Treat categories as a way to reduce the search space rather than as a promise about exactly how a game plays.", "BrainrotGames separates categories so visitors can explore by theme while still keeping the individual game page available for more context. If a category is not working for you, switching genre is often faster than repeatedly opening similar thumbnails."]],
      ["A quick decision checklist", ["Before opening a game, ask: Do I want a short or long session? Am I on desktop or touch? Do I want reaction speed, problem solving, competition or relaxation? Am I comfortable with the likely controls? If you can answer those four questions, most large browser libraries become much easier to navigate."]]
    ]
  },
  "browser-game-performance": {
    title: "How to Make Browser Games Run Better",
    category: "Performance",
    intro: "When a browser game stutters or takes a long time to load, the cause is not always the game itself. Use this checklist to separate connection problems, browser pressure, device limits and provider-side issues.",
    sections: [
      ["First separate loading from gameplay", ["If the game takes a long time to appear but becomes smooth afterward, the problem is more likely related to the network, caching or the third-party game host. If the game loads quickly but stutters during play, look at device performance, browser memory use and background activity.", "This distinction saves time because changing graphics settings will not fix a connection that is still downloading assets, and restarting a router will not fix a device that is already running out of memory."]],
      ["Close unnecessary tabs and applications", ["Browser games compete with other tabs for memory and CPU time. Video streams, large web apps and many open tabs can make a game feel less responsive. Before troubleshooting the game itself, close tabs you do not need and pause heavy background applications.", "On a laptop, also check whether the device is running hot. Sustained heat can reduce performance as the system protects itself. A hard surface with clear airflow is preferable to playing on a soft surface that blocks ventilation."]],
      ["Use a current browser", ["Keep the browser updated and test the game in a mainstream current browser if something behaves strangely. Modern browser games often depend on current JavaScript, graphics and media capabilities. A browser that is several versions behind can produce problems that are difficult to diagnose from the game page alone.", "If one browser fails while another works, record that difference rather than repeatedly refreshing. It is useful information when reporting a technical problem."]],
      ["Reduce the variables", ["For persistent stuttering, test one change at a time. Stop background video, disable unnecessary extensions temporarily, reconnect to a stable network and reload the page. If the game then improves, you have identified a likely source without changing everything at once.", "Extensions can occasionally interfere with scripts, frames or media. Private browsing can be a useful diagnostic test because it often starts with a cleaner extension environment, although it is not a permanent fix for a provider-side problem."]],
      ["Know when the issue is outside your control", ["Some games are delivered by third-party providers. A provider can change, update or temporarily remove a game without BrainrotGames changing its page. If a specific game repeatedly fails while other games work normally, report the exact game URL and behavior rather than assuming your device is broken."]]
    ]
  },
  "mobile-browser-gaming": {
    title: "Playing Browser Games on a Phone or Tablet",
    category: "Mobile",
    intro: "Touch devices make browser gaming convenient, but not every game is designed around a small screen. A few checks before you play can prevent most frustrating sessions.",
    sections: [
      ["Check the controls before you start", ["The most important mobile question is whether the game actually makes sense with touch input. A game that expects a precise mouse pointer or several keyboard keys may technically open on a phone but still be uncomfortable to play.", "If the game provides on-screen controls, check their size and position. Keep your fingers away from browser edges and system gestures where possible, especially on smaller screens."]],
      ["Use the right orientation", ["Some games work best in landscape while others are comfortable in portrait. If the game looks cramped, try rotating the device before changing other settings. A wider view can make racing, platform and action games much easier to control.", "If your device keeps rotating unexpectedly, use the device's orientation lock after choosing the position that works for the game."]],
      ["Give the connection a fair test", ["Browser games can load many assets before gameplay starts. On mobile data, a weak or fluctuating connection can make the first load feel much worse than the eventual gameplay. If possible, start on a stable Wi-Fi connection when testing a new game.", "Avoid repeatedly reloading a page on an unstable connection. Give the initial load time to finish and watch whether the game eventually becomes responsive."]],
      ["Watch battery and heat", ["Graphics-heavy games can use substantial battery and make a phone warm. Lowering other background activity and avoiding direct sunlight can help. If the device becomes uncomfortably hot, stop the session and let it cool rather than forcing continued play.", "Battery-saving modes can also change performance behavior. If a game suddenly becomes less responsive after enabling a power-saving mode, test again later under normal conditions."]],
      ["Know when desktop is the better choice", ["If a game depends on a keyboard, precise mouse movement or a large interface, switching to desktop is not a failure of the phone. The goal is to choose the device that fits the game's interaction model. BrainrotGames supports discovery across categories, but individual third-party games can have different device requirements."]]
    ]
  },
  "puzzle-game-strategy": {
    title: "Better Puzzle-Game Decisions: A Simple Strategy Guide",
    category: "Puzzles",
    intro: "Puzzle games reward attention more than frantic clicking. The same few habits work across matching, grid, logic and pattern-based games even when the rules are different.",
    sections: [
      ["Look for the next two moves", ["A common beginner mistake is choosing the move that looks best immediately. Before committing, spend a few seconds asking what the board will look like afterward. A smaller immediate gain can be stronger if it creates multiple future options.", "This is especially useful in grid and matching games where one move changes several nearby pieces. Train yourself to inspect the result of a move before making it rather than reacting to the current board alone."]],
      ["Protect flexibility", ["When several choices are available, prefer moves that leave multiple legal responses. A move that puts the board into a narrow state may score well once but make the next turn difficult.", "Flexibility matters in logic games too. If one assumption eliminates most possible solutions, verify it before building the rest of the puzzle around it."]],
      ["Separate recognition from action", ["Fast games encourage instant reactions, but puzzle games often reward a short pause. First identify the pattern or constraint; then choose the move. Mixing those steps can cause avoidable mistakes because you act before you have finished evaluating the board.", "If you repeatedly make the same type of error, name it. For example: missing a second match, overlooking an empty square, or committing to an unverified assumption. A named mistake is easier to correct than a vague feeling of being unlucky."]],
      ["Reset your attention", ["Long puzzle sessions can create tunnel vision. If the board seems impossible, look away for a few seconds and return with a fresh scan. The reset is useful because it changes what you notice, not because the puzzle itself has changed.", "For timed puzzles, practice the same habit during training sessions so that pausing does not feel like failure. A controlled reset is often faster than repeatedly making the same mistake."]],
      ["Use difficulty as feedback", ["If you solve every puzzle instantly, try a harder category or rule set. If you fail repeatedly without understanding why, step down and learn the pattern first. Good difficulty creates a reason to change your decision process; it should not simply produce repeated frustration."]]
    ]
  },
  "browser-racing-tips": {
    title: "Browser Racing Games: Improve Your Lap Times",
    category: "Racing",
    intro: "You do not need a racing wheel to improve at browser racing games. Consistency, braking control and learning the track usually matter more than making every corner look dramatic.",
    sections: [
      ["Learn the track before chasing speed", ["Your first laps should be reconnaissance. Identify where the track tightens, where visibility changes and where you can safely accelerate. Trying to set a record before knowing the layout usually leads to repeated crashes in the same places.", "Once the route feels familiar, start measuring improvement by consistency: how many clean laps can you complete rather than how fast one perfect-looking corner was?"]],
      ["Brake before the corner", ["A common mistake is carrying too much speed into a turn and then using steering to recover. Braking earlier creates a slower entry but a cleaner exit. In many arcade-style racing games, the speed you carry out of the corner matters more than the few milliseconds gained on entry.", "Use a simple experiment: take the same corner three times, braking earlier each time, and compare how quickly you can accelerate afterward. This teaches the game's handling model faster than guessing."]],
      ["Use a repeatable racing line", ["The exact ideal line depends on the game, but the principle is consistent: use the available track space to make corners less sharp. Approach from a useful outside position, turn toward the apex and use the exit space to straighten the car as you accelerate.", "Do not copy a line mechanically if the game has unusual collision physics. Treat the racing line as a starting model and adapt it to the actual handling."]],
      ["Smooth inputs beat constant corrections", ["Rapid left-right corrections often create instability. Make one deliberate steering input, observe the response and adjust. This is particularly important in keyboard-controlled games where steering can be digital rather than analog.", "If the car feels twitchy, reduce how often you change direction. A stable car is easier to place accurately and gives you more time to think about the next section of track."]],
      ["Practice one corner at a time", ["When a track has one section that repeatedly causes mistakes, make that section your practice target. Learn its braking point, steering input and acceleration point separately. Once it becomes predictable, link it back into a full lap."]]
    ]
  },
  "keyboard-mouse-controls": {
    title: "Keyboard and Mouse Controls: A Quick Reference",
    category: "Controls",
    intro: "Browser games do not share one universal control scheme. This guide explains how to identify controls quickly and avoid the common desktop problems that make a game feel unresponsive.",
    sections: [
      ["Check the game's own instructions first", ["A familiar key does not always mean a familiar action. W, A, S and D are common movement keys, arrow keys are also common, and Space often means jump or confirm, but individual games can use completely different mappings.", "If a game provides an instruction screen, read it before experimenting. It is faster than learning controls through accidental actions, especially in games where the first few seconds matter."]],
      ["Make sure the game has focus", ["If keyboard input seems ignored, click inside the game frame once and try again. Browsers use keyboard focus for many interface elements, so a page control can sometimes receive the key instead of the game.", "If the browser scrolls when you press an arrow key, that is another sign that the game may not have focus. Click the play area and test again."]],
      ["Watch for browser shortcuts", ["Some key combinations belong to the browser or operating system rather than the game. Avoid assuming that every combination will be available to a web game. If a control conflicts with normal browser behavior, use the game's alternative control if one is provided.", "Do not disable security features just to make a game work. A control conflict is usually better solved by changing the game setting or using another supported input."]],
      ["Use a mouse deliberately", ["For pointer-based games, small controlled movements are often better than fast sweeping motions. Keep the pointer inside the game area when the game expects continuous tracking and avoid moving onto other page controls during active play.", "If the game uses drag-and-drop, start the drag from the intended object and release inside the target rather than relying on very fast movements that can be lost by the browser."]],
      ["When controls still fail", ["Test another current browser, reload the page and check whether the issue affects only one game. If several games fail in the same way, the problem may be broader than a single game. If one game fails while the rest work, record its title and URL when contacting BrainrotGames."]]
    ]
  },
  "two-player-browser-games": {
    title: "How to Pick a Good Two-Player Browser Game",
    category: "Two Players",
    intro: "Two-player games can be excellent for a quick shared session, but the best choice depends on how the two players will actually interact with the game.",
    sections: [
      ["Shared device or separate devices?", ["Start by deciding whether both players will use the same keyboard or whether the game supports separate devices or online multiplayer. This changes the type of game that makes sense. Shared-device games need controls that remain readable and reachable for both players.", "If you are unsure, read the game instructions before starting a competitive session. A game may have a multiplayer category without offering the exact local mode you expected."]],
      ["Look for symmetrical controls", ["Good local two-player games usually give each player a clear control area or an obvious set of keys. If the controls overlap heavily, the game can become uncomfortable even when the underlying gameplay is fun.", "When choosing between two similar games, prefer the one where both players can understand their controls without constantly asking the other player which key does what."]],
      ["Short rounds often work best", ["For a shared session, short rounds make it easy to swap turns and keep the result moving. Long games can still work, but they need enough depth to justify the time and a clear way to pause or resume.", "If one player is much more experienced, short rounds also reduce the frustration of being outplayed repeatedly. You can reset, change roles or choose a different challenge without ending the whole session."]],
      ["Choose readability over spectacle", ["Two-player games become harder when important information is tiny, crowded or difficult to distinguish. Look for clear objectives, readable score information and controls that are easy to understand at a glance.", "A simple game with excellent feedback can be much better for two people than a visually complicated game that makes both players spend more time understanding the interface than playing."]],
      ["Keep competition friendly", ["The best multiplayer session is not necessarily the one with the highest score. Choose a game that matches the mood: cooperative if you want to solve something together, competitive if both players want a direct contest, or turn-based if you want a slower pace."]]
    ]
  },
  "how-we-select-games": {
    title: "How BrainrotGames Selects and Maintains Its Game Catalogue",
    category: "Editorial",
    intro: "BrainrotGames uses third-party game distribution services for parts of its playable catalogue. This page explains what the catalogue process can and cannot guarantee, and how our original editorial layer is different from provider-supplied game data.",
    sections: [
      ["Third-party game data is a starting point", ["A game feed gives BrainrotGames useful catalogue information such as a title, identifier, category, artwork and provider URL. That information helps us organize discovery, but a feed entry is not the same thing as an editorial review. Provider data can also change over time.", "For that reason, we treat provider information as operational catalogue data and keep our own guidance separate. We do not present a provider description as if it were a BrainrotGames-written review."]],
      ["Availability needs ongoing checks", ["Browser games can be removed, moved or changed by their provider. BrainrotGames uses conservative availability checks to avoid knowingly presenting certain hard failures, while recognizing that a successful HTTP response does not guarantee perfect gameplay in every browser or device.", "This distinction matters. A provider page can be reachable while a game still has a device-specific issue. We therefore avoid claiming that automated checks can prove every game works for every visitor."]],
      ["Blocked games are deliberately excluded", ["When a game is known to be unavailable or unsuitable for the catalogue, it can be excluded from the playable list and related discovery surfaces. The goal is not to maximize the number of URLs; it is to keep the catalogue useful.", "A smaller catalogue with working, relevant choices is more valuable than a large list filled with dead links or misleading entries."]],
      ["Original editorial content has a different job", ["Our guides are written around practical questions that a game feed cannot answer: how to choose a game for a short session, how to troubleshoot browser performance, how to play comfortably on mobile, and how to improve at common genres.", "This editorial section is intentionally separate from automated catalogue descriptions. The aim is to give visitors information worth reading even before they decide which game to play."]],
      ["Transparency matters", ["Third-party game titles, artwork, trademarks and game content remain the property of their respective rights holders. BrainrotGames provides discovery and browser access where the relevant distribution relationship permits it. If a rights holder has a concern about material presented through the site, our contact page provides a route for raising it."]]
    ]
  }
};

function escapeHtml(value = "") {
  return String(value).replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
}
function slug(value = "") { return String(value).toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function paragraphHtml(lines) { return lines.map(line => `<p>${escapeHtml(line)}</p>`).join(""); }
function articleSchema(article, canonical) {
  return { "@context":"https://schema.org", "@type":"Article", headline:article.title, description:article.intro, datePublished:UPDATED, dateModified:UPDATED, author:{"@type":"Organization",name:"BrainrotGames Editorial Team",url:`${SITE_URL}/about.html`}, publisher:{"@type":"Organization",name:"BrainrotGames",url:`${SITE_URL}/`}, mainEntityOfPage:canonical };
}

export async function onRequestGet(context) {
  const slugValue = slug(context.params.slug || "");
  const article = ARTICLES[slugValue];
  if (!article) return new Response("Guide not found", { status:404, headers:{"content-type":"text/plain; charset=utf-8","cache-control":"no-store"} });
  const canonical = `${SITE_URL}/guides/${slugValue}`;
  const sections = article.sections.map(([heading, paragraphs]) => `<section><h2>${escapeHtml(heading)}</h2>${paragraphHtml(paragraphs)}</section>`).join("");
  const related = Object.entries(ARTICLES).filter(([key]) => key !== slugValue).slice(0,3).map(([key, value]) => `<li><a href="/guides/${key}">${escapeHtml(value.title)}</a></li>`).join("");
  const schema = JSON.stringify(articleSchema(article, canonical)).replace(/</g,"\\u003c");
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><meta name="description" content="${escapeHtml(article.intro.slice(0,155))}"><title>${escapeHtml(article.title)} | BrainrotGames Guides</title><link rel="canonical" href="${canonical}"><link rel="stylesheet" href="/styles.css"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1559302511010806" crossorigin="anonymous"></script><script type="application/ld+json">${schema}</script><style>
.article-page{padding:42px 0 80px}.article-wrap{max-width:860px;margin:0 auto}.article-header{padding:30px 0 34px;border-bottom:1px solid var(--border)}.article-header h1{font-size:clamp(38px,6vw,64px);line-height:1.03;margin:4px 0 16px}.article-intro{color:var(--muted);font-size:18px;line-height:1.8;max-width:780px}.article-meta{color:var(--muted);font-size:12px}.article-body{padding-top:30px}.article-body section{margin-bottom:34px}.article-body h2{font-size:27px;margin:0 0 12px}.article-body p{color:var(--muted);font-size:16px;line-height:1.85;margin:0 0 16px}.article-note{margin-top:40px;padding:22px;border:1px solid var(--border);border-radius:15px;background:rgba(255,255,255,.025)}.article-note p{color:var(--muted);line-height:1.7}.related{margin-top:42px;padding-top:28px;border-top:1px solid var(--border)}.related ul{padding-left:20px}.related li{margin:10px 0}.related a{color:var(--accent2)}.article-back{display:inline-block;margin-top:8px;color:var(--accent2);font-weight:700}@media(max-width:650px){.article-page{padding-top:24px}.article-header h1{font-size:38px}.article-intro{font-size:16px}}
</style></head><body><header class="site-header"><div class="container nav"><a class="brand" href="/" aria-label="BrainrotGames home"><span class="brand-mark">BG</span><span>Brainrot<span>Games</span></span></a><nav aria-label="Main navigation"><a href="/">Home</a><a href="/games">Categories</a><a href="/guides/">Guides</a><a href="/about.html">About</a></nav></div></header><main class="container article-page"><article class="article-wrap"><header class="article-header"><p class="eyebrow">${escapeHtml(article.category.toUpperCase())}</p><h1>${escapeHtml(article.title)}</h1><p class="article-intro">${escapeHtml(article.intro)}</p><p class="article-meta">BrainrotGames Editorial Team · Updated September 9, 2026</p></header><div class="article-body">${sections}</div><aside class="article-note"><strong>About this guide</strong><p>This guide is original BrainrotGames editorial content. It is intended as practical general advice; individual third-party games can have their own controls, rules and technical requirements.</p></aside><section class="related"><h2>More gaming guides</h2><ul>${related}</ul><a class="article-back" href="/guides/">← Back to all guides</a></section></article></main><footer class="site-footer"><div class="container footer-inner"><div class="footer-brand"><strong>BrainrotGames</strong><span>Free browser games and practical gaming guides.</span></div><nav class="footer-links" aria-label="Footer navigation"><a href="/about.html">About Us</a><a href="/contact.html">Contact Us</a><a href="/privacy.html">Privacy Policy</a><a href="/cookies.html">Cookie Policy</a><a href="/terms.html">Terms of Service</a></nav></div></footer></body></html>`;
  return new Response(html, { status:200, headers:{"content-type":"text/html; charset=utf-8","cache-control":"public, max-age=300, s-maxage=1800, stale-while-revalidate=86400"} });
}
